/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication16;
import java.lang.reflect.Array;
import java.util.ArrayList;
/**
 *
 * @author ariq
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_ok = new javax.swing.JButton();
        txtNominal = new javax.swing.JTextField();
        lbl_100rb = new javax.swing.JLabel();
        lbl_50rb = new javax.swing.JLabel();
        lbl_20rb = new javax.swing.JLabel();
        lbl_10rb = new javax.swing.JLabel();
        lbl_5rb = new javax.swing.JLabel();
        lbl_2rb = new javax.swing.JLabel();
        lbl_1rb = new javax.swing.JLabel();
        lbl_500 = new javax.swing.JLabel();
        lbl_200 = new javax.swing.JLabel();
        lbl_100 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_ok.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_ok.setText("Konversi");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        txtNominal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_100rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_100rb.setText("jLabel1");

        lbl_50rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_50rb.setText("jLabel1");

        lbl_20rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_20rb.setText("jLabel2");

        lbl_10rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_10rb.setText("jLabel3");

        lbl_5rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_5rb.setText("jLabel4");

        lbl_2rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_2rb.setText("jLabel5");

        lbl_1rb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_1rb.setText("jLabel6");

        lbl_500.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_500.setText("jLabel7");

        lbl_200.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_200.setText("jLabel8");

        lbl_100.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_100.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_50rb)
                            .addComponent(lbl_100rb)
                            .addComponent(lbl_20rb)
                            .addComponent(lbl_10rb)
                            .addComponent(lbl_5rb))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_ok)
                            .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_2rb)
                    .addComponent(lbl_1rb)
                    .addComponent(lbl_500)
                    .addComponent(lbl_200)
                    .addComponent(lbl_100))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_100rb)
                    .addComponent(lbl_2rb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_50rb)
                    .addComponent(lbl_1rb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_20rb)
                    .addComponent(lbl_500))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_10rb)
                    .addComponent(lbl_200))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_5rb)
                    .addComponent(lbl_100))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        
        int[] listUang = {100000,50000,20000,10000,5000,2000,1000,500,200,100};
        ArrayList<Integer> hasil = new ArrayList();
        int uangInput = Integer.parseInt(txtNominal.getText());
        int i = 0;
        int k = 0;
        while (uangInput!=0) {
            hasil.add(uangInput/listUang[i]);
            uangInput = uangInput % listUang[i];
            k = uangInput % listUang[i];
            i++;
        }
        
        lbl_100rb.setText(String.valueOf(hasil.get(0)));
        lbl_50rb.setText(String.valueOf(hasil.get(1)));
        lbl_20rb.setText(String.valueOf(hasil.get(2)));
        lbl_10rb.setText(String.valueOf(hasil.get(3)));
        lbl_5rb.setText(String.valueOf(hasil.get(4)));
        lbl_2rb.setText(String.valueOf(hasil.get(5)));
        lbl_1rb.setText(String.valueOf(hasil.get(6)));
        lbl_500.setText(String.valueOf(hasil.get(7)));
        lbl_200.setText(String.valueOf(hasil.get(8)));
        lbl_100.setText(String.valueOf(hasil.get(9)));

        
        
        
        
    }//GEN-LAST:event_button_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ok;
    private javax.swing.JLabel lbl_100;
    private javax.swing.JLabel lbl_100rb;
    private javax.swing.JLabel lbl_10rb;
    private javax.swing.JLabel lbl_1rb;
    private javax.swing.JLabel lbl_200;
    private javax.swing.JLabel lbl_20rb;
    private javax.swing.JLabel lbl_2rb;
    private javax.swing.JLabel lbl_500;
    private javax.swing.JLabel lbl_50rb;
    private javax.swing.JLabel lbl_5rb;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
